/*
 * instruction_names.hpp
 *
 *  Created on: Aug 1, 2011
 *      Author: danny
 */

#ifndef INSTRUCTION_NAMES_HPP_
#define INSTRUCTION_NAMES_HPP_

#include "avr_instruction_set.hpp"

namespace avrsim { namespace instructions {
template< typename instruction>
struct instruction_name
{
    static const char *get()
    {
        return "UNKNOWN INSTRUCTION";
    }
};
#define AVRSIM_DECLARE_NAME( instruction) template <> struct instruction_name<instruction> { static const char *get() { return #instruction;}};
AVRSIM_DECLARE_NAME( NOP)
AVRSIM_DECLARE_NAME( MOVW)
AVRSIM_DECLARE_NAME( MULS)
AVRSIM_DECLARE_NAME( MULSU)
AVRSIM_DECLARE_NAME( FMUL)
AVRSIM_DECLARE_NAME( FMULS)
AVRSIM_DECLARE_NAME( FMULSU)
AVRSIM_DECLARE_NAME( CPC)
AVRSIM_DECLARE_NAME( SBC)
AVRSIM_DECLARE_NAME( ADD)
AVRSIM_DECLARE_NAME( CPSE)
AVRSIM_DECLARE_NAME( CP)
AVRSIM_DECLARE_NAME( SUB)
AVRSIM_DECLARE_NAME( ADC)
AVRSIM_DECLARE_NAME( AND)
AVRSIM_DECLARE_NAME( EOR)
AVRSIM_DECLARE_NAME( OR)
AVRSIM_DECLARE_NAME( MOV)
AVRSIM_DECLARE_NAME( CPI)
AVRSIM_DECLARE_NAME( SBCI)
AVRSIM_DECLARE_NAME( SUBI)
AVRSIM_DECLARE_NAME( ORI)
AVRSIM_DECLARE_NAME( ANDI)
AVRSIM_DECLARE_NAME( LDD_Y)
AVRSIM_DECLARE_NAME( LDD_Z)
AVRSIM_DECLARE_NAME( STD_Z)
AVRSIM_DECLARE_NAME( STD_Y)
AVRSIM_DECLARE_NAME( LDS)
AVRSIM_DECLARE_NAME( LD_Z_inc)
AVRSIM_DECLARE_NAME( LD_Z_dec)
AVRSIM_DECLARE_NAME( LD_Z_min)
AVRSIM_DECLARE_NAME( LPM_Z)
AVRSIM_DECLARE_NAME( LPM_Z_inc)
AVRSIM_DECLARE_NAME( ELPM_Z)
AVRSIM_DECLARE_NAME( ELPM_Z_inc)
AVRSIM_DECLARE_NAME( LD_Y_inc)
AVRSIM_DECLARE_NAME( LD_Y_dec)
AVRSIM_DECLARE_NAME( LD_Y_min)
AVRSIM_DECLARE_NAME( LD_Y_2)
AVRSIM_DECLARE_NAME( LD_X_inc)
AVRSIM_DECLARE_NAME( LD_X_dec)
AVRSIM_DECLARE_NAME( LD_X_min)
AVRSIM_DECLARE_NAME( LD_X)
AVRSIM_DECLARE_NAME( POP)
AVRSIM_DECLARE_NAME( STS)
AVRSIM_DECLARE_NAME( ST_Z_inc)
AVRSIM_DECLARE_NAME( ST_Z_dec)
AVRSIM_DECLARE_NAME( ST_Z_min)
AVRSIM_DECLARE_NAME( unk1)
AVRSIM_DECLARE_NAME( ST_Y_inc)
AVRSIM_DECLARE_NAME( ST_Y_dec)
AVRSIM_DECLARE_NAME( ST_Y_min)
AVRSIM_DECLARE_NAME( ST_Y)
AVRSIM_DECLARE_NAME( ST_X_inc)
AVRSIM_DECLARE_NAME( ST_X_dec)
AVRSIM_DECLARE_NAME( ST_X_min)
AVRSIM_DECLARE_NAME( ST_X)
AVRSIM_DECLARE_NAME( PUSH)
AVRSIM_DECLARE_NAME( COM)
AVRSIM_DECLARE_NAME( NEG)
AVRSIM_DECLARE_NAME( SWAP)
AVRSIM_DECLARE_NAME( INC)
AVRSIM_DECLARE_NAME( unk2)
AVRSIM_DECLARE_NAME( ASR)
AVRSIM_DECLARE_NAME( LSR)
AVRSIM_DECLARE_NAME( ROR)
AVRSIM_DECLARE_NAME( DEC)
AVRSIM_DECLARE_NAME( BSET)
AVRSIM_DECLARE_NAME( BCLR)
AVRSIM_DECLARE_NAME( IJMP)
AVRSIM_DECLARE_NAME( EIJMP)
AVRSIM_DECLARE_NAME( RET)
AVRSIM_DECLARE_NAME( ICALL)
AVRSIM_DECLARE_NAME( RETI)
AVRSIM_DECLARE_NAME( EICALL)
AVRSIM_DECLARE_NAME( SLEEP)
AVRSIM_DECLARE_NAME( BREAK)
AVRSIM_DECLARE_NAME( WDR)
AVRSIM_DECLARE_NAME( LPM)
AVRSIM_DECLARE_NAME( ELPM)
AVRSIM_DECLARE_NAME( SPM)
AVRSIM_DECLARE_NAME( ESPM)
AVRSIM_DECLARE_NAME( JMP)
AVRSIM_DECLARE_NAME( CALL)
AVRSIM_DECLARE_NAME( ADIW)
AVRSIM_DECLARE_NAME( SBIW)
AVRSIM_DECLARE_NAME( CBI)
AVRSIM_DECLARE_NAME( SBIC)
AVRSIM_DECLARE_NAME( SBI)
AVRSIM_DECLARE_NAME( SBIS)
AVRSIM_DECLARE_NAME( MUL)
AVRSIM_DECLARE_NAME( IN)
AVRSIM_DECLARE_NAME( OUT)
AVRSIM_DECLARE_NAME( RJMP)
AVRSIM_DECLARE_NAME( RCALL)
AVRSIM_DECLARE_NAME( LDI)
AVRSIM_DECLARE_NAME( BRBS)
AVRSIM_DECLARE_NAME( BRBC)
AVRSIM_DECLARE_NAME( BLD)
AVRSIM_DECLARE_NAME( BST)
AVRSIM_DECLARE_NAME( SBRC)
AVRSIM_DECLARE_NAME( SBRS)
}}


#endif /* INSTRUCTION_NAMES_HPP_ */
